services:
  etl:
    container_name: open-data-etl
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    volumes:
      - ./data:/app/data
      - ./tests:/app/tests

    restart: "no"
