services:
  etl:
    container_name: open-data-etl
    build:
      context: .
      dockerfile: Dockerfile
      target: development

    env_file:
      - .env

    volumes:
      - ./data:/app/data

    restart: "no"