[project]
name = "open-data-etl-platform"
version = "0.1.0"
description = "Open data ETL platform for learning Data Engineering, DevOps and Cloud."
requires-python = ">3.12, <3.13"

dependencies = [
    "httpx",
    "pydantic-settings",
    "pandas",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

[build-system]
requires = ["setuptools>=70"]
build-backend = "setuptools.build_meta"